platform :android do
  desc "Build a Flutter apk"
  lane :build do
    Dir.chdir("..") do
      sh "flutter packages get"
      sh "flutter clean"
      sh "flutter build apk"
    end
  end
end

platform :ios do
  desc "Build an ipa"
  lane :build do |options|
    Dir.chdir("..") do
      sh "flutter packages get"
      sh "flutter clean"
      sh "flutter build ios"
    end

    build_ios_app(
      workspace: "./ios/Runner.xcworkspace",
      scheme: "Runner",
      clean: true,
      output_directory: './build',
      output_name: "TicTacToe.ipa"
    )
  end
end
