name: Validate Pull Request
on:
  pull_request_target:
    branches:
      - develop
jobs:
  setup: Setup dependencies
  if: github.event.pull_request.head.repo.full_name != github.repository
  runs-on: macos-latest
  steps:
    - name: Checkout Project
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: "12.x"
        cache: 'gradle'

    - name: Setup Flutter
      uses: subosito/flutter-action@v1
      with:
        channel: "stable"
        cache: true

    - name: Pub Get Packages
      run: flutter pub get

  lint:
    name: Run linter
    if: github.event.pull_request.head.repo.full_name != github.repository
    runs-on: macos-latest
    steps:
      - name: Run linter
        run: flutter analyze

  test:
    name: Run tests
    if: github.event.pull_request.head.repo.full_name != github.repository
    runs-on: macos-latest
    steps:
      - name: Running tests
        run: flutter test
