name: Validate Pull Request

on:
  pull_request:
    branches:
      - develop

jobs:
  analyze:
    name: Analyze
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable

    - name: Install dependencies
      run: flutter pub get

    - name: Analyze code
      run: flutter analyze

  test:
    name: Test
    runs-on: macos-latest
    needs: [analyze]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable

    - name: Install dependencies
      run: flutter pub get

    - name: Run tests
      run: flutter test

  build:
    name: Build
    runs-on: macos-latest
    needs: [test]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable

    - name: Build APK
      run: fastlane ios build
